import { useEffect, useState } from "react";
import axios from "axios";
import { ArrowLeft, Eye, Inbox, LogOut, Plus, Save, Trash2, Users } from "lucide-react";

const API = import.meta.env.VITE_API_URL || "http://localhost:5000/api";
const auth = () => ({ Authorization: `Bearer ${localStorage.getItem("portfolio_owner_token") || ""}` });
const field = (label, value, onChange, area=false) => <label><span>{label}</span>{area?<textarea rows="3" value={value||""} onChange={e=>onChange(e.target.value)}/>:<input value={value||""} onChange={e=>onChange(e.target.value)}/>}</label>;

export default function OwnerStudio({ seed }) {
  const [token,setToken]=useState(localStorage.getItem("portfolio_owner_token")||"");
  const [login,setLogin]=useState({email:"",password:""}),[content,setContent]=useState(seed),[tab,setTab]=useState("content"),[message,setMessage]=useState(""),[messages,setMessages]=useState([]),[visitors,setVisitors]=useState([]);
  useEffect(()=>{if(token)loadContent()},[token]);
  async function signIn(e){e.preventDefault();try{const {data}=await axios.post(`${API}/admin/login`,login);localStorage.setItem("portfolio_owner_token",data.token);setToken(data.token);setMessage("");}catch(x){setMessage(x.response?.data?.message||"Login failed")}}
  async function loadContent(){try{const {data}=await axios.get(`${API}/admin/content`,{headers:auth()});setContent(data.content||seed)}catch(x){if(x.response?.status===401)logout();else setMessage("Could not load content")}}
  async function save(){try{await axios.put(`${API}/admin/content`,content,{headers:auth()});setMessage("Portfolio published successfully");}catch(x){setMessage(x.response?.data?.message||"Save failed")}}
  async function loadMessages(){setTab("messages");const {data}=await axios.get(`${API}/admin/messages`,{headers:auth()});setMessages(data.messages||[])}
  async function loadVisitors(){setTab("visitors");const {data}=await axios.get(`${API}/admin/visitors`,{headers:auth()});setVisitors(data.visitors||[])}
  function logout(){localStorage.removeItem("portfolio_owner_token");setToken("")}
  if(!token)return <main className="owner-login"><form onSubmit={signIn}><a href="/"><ArrowLeft/> Public portfolio</a><h1>Owner Studio</h1><p>Securely edit your portfolio without changing code.</p><label><span>Owner email</span><input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label><span>Password</span><input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label>{message&&<b className="owner-error">{message}</b>}<button>Sign in</button></form></main>;
  const update=(section,value)=>setContent({...content,[section]:value});
  return <main className="owner-studio"><aside><h2>Gowtham Studio</h2><button className={tab==="content"?"active":""} onClick={()=>setTab("content")}><Save/> Content</button><button className={tab==="messages"?"active":""} onClick={loadMessages}><Inbox/> Messages</button><button className={tab==="visitors"?"active":""} onClick={loadVisitors}><Users/> Visitors</button><a href="/" target="_blank"><Eye/> View public site</a><button onClick={logout}><LogOut/> Logout</button></aside><section className="owner-workspace"><header><div><small>OWNER-ONLY CONTROL</small><h1>{tab==="content"?"Portfolio Content":tab==="messages"?"Contact Messages":"Visitor Activity"}</h1></div>{tab==="content"&&<button className="owner-save" onClick={save}><Save/> Save & Publish</button>}</header>{message&&<div className="owner-notice">{message}</div>}
    {tab==="content"&&<div className="owner-sections"><Editor title="Profile"><div className="owner-grid">{["name","shortName","role","headline","email","phone","location","github","linkedin"].map(k=><span key={k}>{field(k,content.profile?.[k],v=>update("profile",{...content.profile,[k]:v}),k==="description")}</span>)}</div>{field("description",content.profile?.description,v=>update("profile",{...content.profile,description:v}),true)}</Editor><ListEditor title="Skills" rows={content.skills||[]} blank={{title:"",icon:"✦",text:""}} fields={["title","icon","text"]} onChange={v=>update("skills",v)}/><ListEditor title="Projects" rows={content.projects||[]} blank={{title:"",category:"Full Stack",description:"",tags:[],style:"blue",liveUrl:"",repoUrl:""}} fields={["title","category","description","tags","style","liveUrl","repoUrl"]} areas={["description"]} onChange={v=>update("projects",v)}/><ListEditor title="Experience" rows={content.experience||[]} blank={{period:"",type:"",company:"",title:"",description:"",skills:[]}} fields={["period","type","company","title","description","skills"]} areas={["description"]} onChange={v=>update("experience",v)}/><Editor title="Education"><div className="owner-grid">{["degree","college","year"].map(k=><span key={k}>{field(k,content.education?.[k],v=>update("education",{...content.education,[k]:v}))}</span>)}</div></Editor></div>}
    {tab==="messages"&&<div className="owner-table">{messages.map(x=><article key={x._id}><div><b>{x.name}</b><a href={`mailto:${x.email}`}>{x.email}</a><p>{x.message}</p></div><time>{new Date(x.createdAt).toLocaleString()}</time></article>)}</div>}
    {tab==="visitors"&&<div className="owner-table">{visitors.map(x=><article key={x._id}><div><b>{x.referrer||"Direct visit"}</b><small>{x.path}</small><p>{x.userAgent}</p></div><time>{new Date(x.createdAt).toLocaleString()}</time></article>)}</div>}
  </section></main>;
}
function Editor({title,children}){return <section className="owner-card"><h3>{title}</h3>{children}</section>}
function ListEditor({title,rows,blank,fields,areas=[],onChange}){const change=(i,key,value)=>onChange(rows.map((r,n)=>n===i?{...r,[key]:["tags","skills"].includes(key)?value.split(",").map(x=>x.trim()).filter(Boolean):value}:r));return <Editor title={title}><div className="owner-list">{rows.map((row,i)=><article key={i}><div className="owner-grid">{fields.map(k=><span key={k}>{field(k,Array.isArray(row[k])?row[k].join(", "):row[k],v=>change(i,k,v),areas.includes(k))}</span>)}</div><button className="owner-delete" onClick={()=>onChange(rows.filter((_,n)=>n!==i))}><Trash2/> Remove</button></article>)}</div><button className="owner-add" onClick={()=>onChange([...rows,blank])}><Plus/> Add {title.replace(/s$/,"")}</button></Editor>}
